# Generated by Django 4.2.4 on 2023-08-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_invited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='invited_by_code',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
    ]
